[metadata]
format.version = "1.1"

[versions]
edc = "0.18.0"
shadow = "9.6.1"

[libraries]
edc-controlplane-base-bom = { module = "org.eclipse.edc:controlplane-base-bom", version.ref = "edc" }
edc-crawler-spi = {module = "org.eclipse.edc:crawler-spi", version.ref = "edc"}
edc-data-plane-spi = { module = "org.eclipse.edc:data-plane-spi", version.ref = "edc" }
edc-dataplane-base-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }
edc-transfer-spi = { module = "org.eclipse.edc:transfer-spi", version.ref = "edc" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
