name: Build to branch

on:
  push:
    branches: 
      - main
      
jobs:
  buidl-to-branch:
    name: Build and push to branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: Cache dependencies 
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: yarn-deps-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn

      - name: Transpile to JavaScript
        run: yarn transpile
        
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
