name: Pull request testing

on:
  push:
    branches-ignore: 
      - main
    paths:
      - '.github/workflows/pull-request-testing.yml'
      - 'jest.config.ts'
      - 'src/**/*.ts'
      - 'tests/**/*.ts'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dependencies:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache dependencies 
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: yarn-deps-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn

  unit:
    name: Unit and integration tests
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker environment
        uses: isbang/compose-action@v1.1.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache dependencies 
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: yarn-deps-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn

      - name: Run tests
        run: yarn test
        env:
          CI: true
