name: test

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker environment
        run: |
          docker compose up --wait
          docker compose logs -f > logs &

      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: yarn-deps-${{ hashFiles('**/yarn.lock') }}


      - name: Install dependencies
        run: |
          yarn

      - name: Run tests
        run: yarn test
        env:
          CI: true

      - name: Print docker logs
        if: failure()
        run: |
          cat logs
